# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    mkdir -p /tmp/artifacts
    mkdir -p /tmp/artifacts/schedules
    cp *py /tmp/artifacts
    cp *txt /tmp/artifacts
    cp schedules/* /tmp/artifacts/schedules
  displayName: 'Generate Artifacts'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'PTSCScheduler'
    targetPath: '/tmp/artifacts'
